### ISSUE TITLE
README content needs updating.

### ISSUE THREAD

**Issue by joshuamckenty** [cf-platform-eng/kafka-service-broker#1]
Can you include some basic description of the broker (limitations, requirements for install, etc) and install instructions?

**Comment by sorvis** [comment]
Another thing that needs updated is I found that to build kafka-service-broker/kafka-broker there is also a dependency on kafka-service-broker/kafka-util The util actually fails because the tests are pointed to some kafka instance. The solution was to build the util using `mvn install -DskipTests` then when I went back and built kafka-broker it succeed in building

**Comment by JaredGordon** [comment]
Thanks sorvis, good suggestion. I'll fix this.

**Comment by JaredGordon** [comment]
Josh, forgot to let you know: I updated the docs back when you created this issue, hope the updates help.

**Comment by JaredGordon** [comment]
sorvis, I've updated the code so that the tests won't get in the way during a build.
